enhavo_app:
    template_paths:
        enhavo_media_library:
            alias: EnhavoMediaLibrary
            path: '@EnhavoMediaLibraryBundle/Resources/views'
            priority: 10
    roles:
        enhavo_media_library_file_index:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_FILE_INDEX
            label: media_library.role.file.label.index
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_file_create:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_FILE_CREATE
            label: media_library.role.file.label.create
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_file_update:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_FILE_UPDATE
            label: media_library.role.file.label.update
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_file_delete:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_FILE_DELETE
            label: media_library.role.file.label.delete
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_tag_index:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_TAG_INDEX
            label: media_library.role.tag.label.index
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_tag_create:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_TAG_CREATE
            label: media_library.role.tag.label.create
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_tag_update:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_TAG_UPDATE
            label: media_library.role.tag.label.update
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_tag_delete:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_TAG_DELETE
            label: media_library.role.tag.label.delete
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_item_index:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_ITEM_INDEX
            label: media_library.role.item.label.index
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_item_create:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_ITEM_CREATE
            label: media_library.role.item.label.create
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_item_update:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_ITEM_UPDATE
            label: media_library.role.item.label.update
            translation_domain: EnhavoMediaLibraryBundle
        enhavo_media_library_item_delete:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_ITEM_DELETE
            label: media_library.role.item.label.delete
            translation_domain: EnhavoMediaLibraryBundle

enhavo_media_library:
    constraints:
        -   Enhavo\Bundle\MediaLibraryBundle\Validator\Constraints\UniqueBasename: ~
        -   Enhavo\Bundle\MediaLibraryBundle\Validator\Constraints\UniqueChecksum: ~
    content_type:
        audio:
            label: 'media_library.content_type.audio'
            translation_domain: EnhavoMediaLibraryBundle
            icon: 'icon-file_audio'
            mime_types:
                - ^audio/.+
        archive:
            label: 'media_library.content_type.archive'
            translation_domain: EnhavoMediaLibraryBundle
            icon: 'icon-archive'
            mime_types:
                - application/gzip
                - application/zip
                - application/x-tar
                - application/x-gtar
        document:
            label: 'media_library.content_type.document'
            translation_domain: EnhavoMediaLibraryBundle
            icon: 'icon-file_document'
            mime_types:
                - application/pdf
                - application/postscript
                - application/rtc
                - application/rtf
                - ^application/ms.+
                - ^application/vnd.+
        text:
            label: 'media_library.content_type.text'
            translation_domain: EnhavoMediaLibraryBundle
            icon: 'icon-file_text'
            mime_types:
                - ^text/.+
        image:
            label: 'media_library.content_type.image'
            translation_domain: EnhavoMediaLibraryBundle
            icon: 'icon-image'
            mime_types:
                - ^image/.+
        video:
            label: 'media_library.content_type.video'
            translation_domain: EnhavoMediaLibraryBundle
            icon: 'icon-file_video'
            mime_types:
                - ^video/.+

enhavo_media:
    formats:
        enhavoMediaLibraryImage:
            type: image
            width: 512
            height: 512
        enhavoMediaLibraryTxt:
            type: text_image
        enhavoMediaLibraryPdf:
            type: pdf_image
            method: ghostscript
        enhavoMediaLibraryVideo:
            type: video_image
        enhavoMediaLibraryThumb:
            -
                type: mimetype
                format: enhavoMediaLibraryTxt
                mimetypes: [text/plain, text/css]
            -
                type: mimetype
                format: enhavoMediaLibraryPdf
                mimetypes: [application/pdf]
            -
                type: mimetype
                format: enhavoMediaLibraryImage
                mimetypes: [image/jpg, image/png, image/jpeg, image/bmp]
            -
                type: mimetype
                format: enhavoMediaLibraryVideo
                mimetypes: [video/mp4]

enhavo_taxonomy:
    taxonomies:
        media_library_tag:
            label: media_library.label.tag
            translation_domain: EnhavoMediaLibraryBundle

enhavo_doctrine_extension:
    metadata:
        Enhavo\Bundle\MediaLibraryBundle\Entity\File:
            extends: Enhavo\Bundle\MediaBundle\Entity\File
            discrName: 'extension'

doctrine:
    orm:
        resolve_target_entities:
            Enhavo\Bundle\MediaBundle\Model\FileInterface: Enhavo\Bundle\MediaLibraryBundle\Entity\File
            Enhavo\Bundle\MediaLibraryBundle\Model\ItemInterface: Enhavo\Bundle\MediaLibraryBundle\Entity\Item
